### ISSUE TITLE
Вопрос для чего нужна страница импорт/экспорт?

### ISSUE THREAD

**Issue by w3prog** [EvgeniyGor/StudentRecords#18]
Какой функционал включает в себя данная страница и почему её нельзя заменить просто кнопкой?

**Comment by EvgeniyGor** [comment]
В [требованиях](https://github.com/EvgeniyGor/StudentRecords/wiki/%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%83#2.2) описано, что администратор должен иметь интерфейс для доступа к любым данным в БД. Изначально предполагал, что страница обеспечит данную функциональность, однако кажется более логичным заменить ее на страницу стандартной админки Django + добавить туда возможность экспорта в файлы.

**Comment by TatyanaBerlenko** [comment]
Вы предлагаете сделать отдельную страницу импорта/экспорта, используя административную панель Django? Или это будет страница фильтрации/управления данными, на которой будет возможность импорта/экспорта?

**Comment by EvgeniyGor** [comment]
Админка предоставляет интерфейс для управления данными в БД. Предлагаю на этих страницах добавить кнопки экспорта, при нажатии на которые будет происходить скачивание отображаемых в текущий момент данных.
