### ISSUE TITLE
Утверждение требований к проекту

### ISSUE THREAD

**Issue by EvgeniyGor** [EvgeniyGor/StudentRecords#23]
В вики постарался формализовать [требования к проекту](https://github.com/EvgeniyGor/StudentRecords/wiki/%D0%A2%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D0%BA-%D0%BF%D1%80%D0%BE%D0%B5%D0%BA%D1%82%D1%83). Хочу получить фидбек о том, чего не хватает или что было понятно неверно.

**Comment by w3prog** [comment]
Начем расписание поставляются формате excel, я знаю что сложно будет, но все же постарайся сделать способ импортирования данных из этого формата, в таблицу с расписанием.

Кто в твоем приложении будет проставлять посещаемость занятий?
 Староста: просмотр и редактирование данных о посещаемости по предметам группы старосты.
Может быть просто вводить, а не редактировать?
Студент: просмотр данных о посещаемости по предметам группы студента.
Тут не понятно зачем студенту видеть посещаемость по своей группе.
Списки тем курсовых работ
Студент: просмотр любых данных о курсовых работах, редактирование своих данных что под этим подразумевается?
Он может видеть чужие курсовые работы?
Список страниц приложения
Управление данными это админка Django или что-то другое?

Можешь перечислить какие данные о себе может ввести студент в систему?

**Comment by EvgeniyGor** [comment]
Насколько понял, посещаемость занятий могут отмечать старосты и преподаватели.

`Может быть просто вводить, а не редактировать?`
А если ошибся, то все? Только через админов править?

`Тут не понятно зачем студенту видеть посещаемость по своей группе`
Наверное незачем. Но и ничего страшного не вижу в том, чтобы студент мог ее видеть.

`Студент: просмотр любых данных о курсовых работах, редактирование своих данных что под этим подразумевается? Он может видеть чужие курсовые работы?`
Данные по курсовым работам на текущий момент - тема и ссылка на репозиторий. Да, студенты могут видеть эту информацию.

`Управление данными это админка Django или что-то другое?`
Это отдельная страница, доступная группе администраторов, где есть возможность редактировать/удалять/добавлять данные о студентах

`Можешь перечислить какие данные о себе может ввести студент в систему?`
Насколько понял, студент никаких данных о себе не вводит.

Создал [issue]( #27) с вопросом о данных пользователей.
