### ISSUE TITLE
Данные пользователей

### ISSUE THREAD

**Issue by EvgeniyGor** [EvgeniyGor/StudentRecords#27]
Личные данные пользователей вводят администраторы или нужно требовать их при регистрации? Нужна ли отдельная страница с профилем пользователя, где он мог бы редактировать данные о себе (для всех групп пользователей)?

**Comment by w3prog** [comment]
Вопрос как происходит регистрация новых пользователей в кафедральных приложениях, для всех групп: студент, староста, преподаватель и админ. Плюс какие данные нужно вводить при регистрации, и кто будет иметь возможность их редактировать и в каком объеме.

**Comment by krinkin** [comment]
пока предполагаем, что регистрация производится администратором. В реальности, студенты будут заполнять гуглоформу, указывая емайл, а потом на этот емайл будет отправляться ссылка для смены пароля
